spring:
  datasource:
    url: jdbc:postgresql://jt_postgres:5432/jt_alerts
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
